version: '3.7'

services:

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: travel_management
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  test_db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: test_db
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
